global using Autofac;
global using Azure.Identity;
global using Azure.Security.KeyVault.Secrets;
global using LeaderAnalytics.AdaptiveClient;
global using LeaderAnalytics.Core;
global using Microsoft.Extensions.Configuration;
global using System.Drawing;
global using System.Drawing.Drawing2D;
global using System.Drawing.Imaging;
