# stage / job / step / task
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/Blog.API/Blog.API.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: 'Pay as you go subscription'
  appName: 'SamWheatWeb'
  system.debug: false

steps:

# Build and deploy API        

- task: UseDotNet@2
  displayName: 'Use dotnet 6'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'DotNet Restore NuGet packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'LeaderAnalyticsFeed'
    includeNuGetOrg: true
 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'DotNet publish'
  inputs:
    command: publish
    publishWebProjects: true
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingdirectory) --self-contained'
    zipAfterPublish: true

- task: AzureRmWebAppDeployment@4
  displayName: 'AzureRmWebAppDeployment@3'
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: $(azureSubscription)
    appType: webApp
    WebAppName: $(appName)
    UseWebDeploy: true
    virtualApplication: '/api'
    packageforLinux: '$(Build.ArtifactStagingDirectory)/*.zip'


# Install dependencies

- script: |
    npm install -g @angular/cli
  displayName: Install Angular CLI

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'


# Build and deploy WebApp

- script: |
    cd Blog/ClientApp
    npm install
  displayName: 'npm install'
     
- script: |
    cd Blog/ClientApp
    npm run build:prod
  displayName: 'npm build'
      
- task: CopyFiles@2
  inputs:
    Contents: 'Blog/ClientApp/dist/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'
        
- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webApp
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/web/Blog/ClientApp/dist/'

# Build and execute database migrations

- task: DotNetCoreCLI@2
  displayName: 'DotNet publish'
  inputs:
    command: publish
    projects: '**/Blog.MigrationFactories.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingdirectory) --self-contained'
    zipAfterPublish: true

- script: |
    cd $(Agent.BuildDirectory)
    cd s/Blog.MigrationFactories/bin/Release/net6.0
    Blog.MigrationFactories.exe
  displayName: 'Deploy Database Migrations'