# stage / job / step / task
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/Blog.API/Blog.API.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  azureSubscription: 'Pay as you go subscription'
  appName: 'SamWheatWeb'
  system.debug: false

steps:

# Install dependencies

- task: NodeTool@0
  displayName: Install Node
  inputs:
    versionSpec: '16.13.1'

- script: |
    npm install -g npm@8.3.0
  displayName: Update NPM

- script: |
    npm install -g @angular/cli
  displayName: Install Angular CLI

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'


# Build and deploy WebApp

- script: |
    cd Blog/ClientApp
    npm install
  displayName: 'npm install'
     
- script: |
    cd Blog/ClientApp
    npm run build:prod
  displayName: 'npm build'
      
- task: CopyFiles@2
  inputs:
    Contents: 'Blog/ClientApp/dist/**' 
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'
        
- task: AzureWebApp@1
  displayName: 'Deploy Azure Web App'
  inputs:
    azureSubscription: $(azureSubscription)
    appType: webApp
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/web/Blog/ClientApp/dist/'

